### PR TITLE
Add integration test for time sensor (#63)

### LINKED ISSUE #63: Integration test for time sensor
Integration test for time sensor, introduced in #48

### PR DESCRIPTION
**Pull request by kevinwallimann**
Closes #63

### CODE REVIEW

File: src/test/scala/za/co/absa/hyperdrive/trigger/scheduler/sensors/time/TimeSensorIntegrationTest.scala [hunk 1]
```diff
@@ -0,0 +1,112 @@
...
+    val properties = Properties(-1L, Settings(Map("cronExpression" -> cronExpression, "quartzJobId" -> quartzJobId), Map.empty), Map.empty)
+    val sensor = Sensor(-1L, SensorTypes.Time, properties)
+
+    val jobParameters1 = JobParameters(Map("deploymentMode" -> "client", "jobJar" -> "spark-job.jar", "mainClass" -> "TheMainClass"), Map.empty)
+    val jobDefinition1 = JobDefinition(-1L, "Time-Sensor Job 1", JobTypes.Spark, jobParameters1, 1)
+    val jobParameters2 = JobParameters(Map("deploymentMode" -> "client", "jobJar" -> "spark-job-2.jar", "mainClass" -> "TheMainClass"), Map.empty)
+    val jobDefinition2 = JobDefinition(-1L, "Time-Sensor Job 2", JobTypes.Spark, jobParameters2, 2)
+
+    val dagDefinitionJoined = DagDefinitionJoined(-1L, Seq(jobDefinition1, jobDefinition2))
+    val workflowJoined = WorkflowJoined("Time-Sensor Workflow", isActive = true, "some-project", LocalDateTime.now(), updated = None, sensor, dagDefinitionJoined)
```
Comment (Zejnilovic) [inline src/test/scala/za/co/absa/hyperdrive/trigger/scheduler/sensors/time/TimeSensorIntegrationTest.scala]: Not sure if you checked, but:
```
TimeSensorIntegrationTest.scala:78: error: not enough arguments for method apply: (name: String, isActive: Boolean, project: String, created: java.time.LocalDateTime, updated: Option[java.time.LocalDateTime], sensor: za.co.absa.hyperdrive.trigger.models.Sensor, dagDefinitionJoined: za.co.absa.hyperdrive.trigger.models.DagDefinitionJoined, id: Long)za.co.absa.hyperdrive.trigger.models.WorkflowJoined in object WorkflowJoined.
[ERROR] Unspecified value parameters project, created, sensor, ...
[ERROR]     val workflowJoined = WorkflowJoined("Time-Sensor Workflow", isActive = true, "some-project", LocalDateTime.now(), updated = None, sensor, dagDefinitionJoined)
```

**Review by jozefbakus — APPROVED** [review]
👍
